---
# Coordinator Config ConfigMap
# NOTE: You'll create this from your local file:
# kubectl create configmap coordinator-config \
#   --from-file=coordinator_config.yaml=../../coordinator_config.yaml \
#   -n protean

---
# Test Plan ConfigMap
# NOTE: You'll create this from your local file:
# kubectl create configmap test-plan \
#   --from-file=test_plan.yaml=../../test_plan.yaml \
#   -n protean

---
# Example of inline ConfigMap (if you want to embed config)
apiVersion: v1
kind: ConfigMap
metadata:
  name: worker-env
  namespace: protean
data:
  RUST_LOG: "info"
  RUST_BACKTRACE: "1"
  N_WORKERS: "3"
  MAX_ACTORS: "2000"
